set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN R17 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports clk_65m_1]
set_property PACKAGE_PIN H17 [get_ports clk_65m_1]

set_property IOSTANDARD LVCMOS33 [get_ports clk_65m_2]
set_property PACKAGE_PIN F17 [get_ports clk_65m_2]


set_property PACKAGE_PIN F16 [get_ports {ad2_in[0]}]
set_property PACKAGE_PIN F20 [get_ports {ad2_in[1]}]
set_property PACKAGE_PIN F19 [get_ports {ad2_in[2]}]
set_property PACKAGE_PIN G20 [get_ports {ad2_in[3]}]
set_property PACKAGE_PIN G19 [get_ports {ad2_in[4]}]
set_property PACKAGE_PIN H18 [get_ports {ad2_in[5]}]
set_property PACKAGE_PIN J18 [get_ports {ad2_in[6]}]
set_property PACKAGE_PIN L20 [get_ports {ad2_in[7]}]
set_property PACKAGE_PIN L19 [get_ports {ad2_in[8]}]
set_property PACKAGE_PIN M20 [get_ports {ad2_in[9]}]
set_property PACKAGE_PIN M19 [get_ports {ad2_in[10]}]
set_property PACKAGE_PIN K18 [get_ports {ad2_in[11]}]



set_property PACKAGE_PIN H20 [get_ports {ad1_in[1]}]
set_property PACKAGE_PIN J20 [get_ports {ad1_in[0]}]
set_property PACKAGE_PIN L17 [get_ports {ad1_in[3]}]
set_property PACKAGE_PIN L16 [get_ports {ad1_in[2]}]
set_property PACKAGE_PIN M18 [get_ports {ad1_in[5]}]
set_property PACKAGE_PIN M17 [get_ports {ad1_in[4]}]
set_property PACKAGE_PIN D20 [get_ports {ad1_in[7]}]
set_property PACKAGE_PIN D19 [get_ports {ad1_in[6]}]
set_property PACKAGE_PIN E19 [get_ports {ad1_in[9]}]
set_property PACKAGE_PIN E18 [get_ports {ad1_in[8]}]
set_property PACKAGE_PIN G18 [get_ports {ad1_in[11]}]
set_property PACKAGE_PIN G17 [get_ports {ad1_in[10]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad1_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad2_in[0]}]

set_property PACKAGE_PIN U14 [get_ports {DataA[0]}]
set_property PACKAGE_PIN U15 [get_ports {DataA[1]}]
set_property PACKAGE_PIN N17 [get_ports {DataA[2]}]
set_property PACKAGE_PIN P18 [get_ports {DataA[3]}]
set_property PACKAGE_PIN W14 [get_ports {DataA[4]}]
set_property PACKAGE_PIN Y14 [get_ports {DataA[5]}]
set_property PACKAGE_PIN V15 [get_ports {DataA[6]}]
set_property PACKAGE_PIN W15 [get_ports {DataA[7]}]
set_property PACKAGE_PIN Y16 [get_ports {DataA[8]}]
set_property PACKAGE_PIN Y17 [get_ports {DataA[9]}]
set_property PACKAGE_PIN P14 [get_ports {DataA[10]}]
set_property PACKAGE_PIN R14 [get_ports {DataA[11]}]
set_property PACKAGE_PIN W18 [get_ports {DataA[12]}]
set_property PACKAGE_PIN W19 [get_ports {DataA[13]}]

set_property PACKAGE_PIN P16 [get_ports WRTA]
set_property PACKAGE_PIN P15 [get_ports ClkA]


set_property PACKAGE_PIN U17 [get_ports ClkB]
set_property PACKAGE_PIN T16 [get_ports WRTB]


set_property PACKAGE_PIN V18 [get_ports {DataB[13]}]
set_property PACKAGE_PIN V17 [get_ports {DataB[12]}]
set_property PACKAGE_PIN T15 [get_ports {DataB[11]}]
set_property PACKAGE_PIN T14 [get_ports {DataB[10]}]
set_property PACKAGE_PIN V13 [get_ports {DataB[9]}]
set_property PACKAGE_PIN U13 [get_ports {DataB[8]}]
set_property PACKAGE_PIN W13 [get_ports {DataB[7]}]
set_property PACKAGE_PIN V12 [get_ports {DataB[6]}]
set_property PACKAGE_PIN U12 [get_ports {DataB[5]}]
set_property PACKAGE_PIN T12 [get_ports {DataB[4]}]
set_property PACKAGE_PIN T10 [get_ports {DataB[3]}]
set_property PACKAGE_PIN T11 [get_ports {DataB[2]}]
set_property PACKAGE_PIN A20 [get_ports {DataB[1]}]
set_property PACKAGE_PIN B19 [get_ports {DataB[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports ClkA]
set_property IOSTANDARD LVCMOS33 [get_ports ClkB]
set_property IOSTANDARD LVCMOS33 [get_ports WRTA]
set_property IOSTANDARD LVCMOS33 [get_ports WRTB]

set_property IOSTANDARD LVCMOS33 [get_ports {DataA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {DataB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN G15 [get_ports uart_tx]
set_property PACKAGE_PIN H15 [get_ports uart_rx]
set_property PACKAGE_PIN M14 [get_ports led]
set_property PACKAGE_PIN N15 [get_ports key]





